name: Pytest
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    env:
      POETRY_VIRTUALENVS_CREATE: "false"

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
        os:
          - macos-14
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}
    name: Pytest ${{ matrix.os }} @ ${{ matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ShellCheck
        if: "${{ contains(matrix.os, 'macos') }}"
        run: |
          brew install shellcheck

      - name: ShellCheck Version
        run: |
          shellcheck --version

      - name: Install Dependencies
        run: |
          python -m pip install -r .github/requirements/requirements-poetry.txt
          poetry install

      - name: Run Tests
        run: python -m pytest
