name: Run ShellCheck
on:
  push:
    paths:
      - .github/workflows/**
    branches:
      - main
      - master
  pull_request:
    paths:
      - .github/workflows/**
  workflow_dispatch:
    inputs:
      SCAN_DIRECTORY:
        default: .github/workflows
        description: The directory containing GitHub workflows YAML files to scan.
        required: false

permissions:
  contents: read

jobs:
  test:
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
      DEFAULT_SCAN_DIRECTORY: .github/workflows

    runs-on: ubuntu-22.04
    name: ShellCheck

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version-file: .github/requirements/python-version.txt

      - name: ShellCheck Version
        run: |
          shellcheck --version

      - name: Install Dependencies
        run: |
          python -m pip install -r .github/requirements/requirements-poetry.txt
          poetry install

      - name: Run ShellCheck
        shell: bash
        env:
          SCAN_DIRECTORY: ${{ inputs.SCAN_DIRECTORY || env.DEFAULT_SCAN_DIRECTORY }}
        run: |
          set -u -o pipefail
          
          cmd_args=()
          test -z "${RUNNER_DEBUG+x}" || cmd_args+=( "--debug" )
          
          poetry run shellcheck-gha "${cmd_args[@]}" -- "$SCAN_DIRECTORY"
