name: Run ShellCheck
on:
  push:
    paths:
      - .github/workflows/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/**
  workflow_dispatch:
    inputs:
      scan-directory:
        default: .github/workflows
        description: The directory containing GitHub workflows YAML files to scan.
        required: false

permissions:
  contents: read

jobs:
  check:
    env:
      DEFAULT_SCAN_DIRECTORY: .github/workflows

    runs-on: ubuntu-22.04
    name: ShellCheck

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run ShellCheck
        uses: ./
        with:
          scan-directory-path: ${{ inputs.scan-directory || env.DEFAULT_SCAN_DIRECTORY }}
